name = "DaphneCipher"
uuid = "5549a73c-5233-4c35-946e-9042ac9299a0"
authors = ["Pierre Abbat <phma@bezitopo.org>"]
version = "0.1.0"

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
OffsetArrays = "1.17.0"
